name: 'MSK Safety Checks'
description: 'Validate MSK cluster, topic, user and ACL'

inputs:
  cluster-name:
    description: 'MSK Cluster Name'
    required: true
  topic-name:
    description: 'Kafka Topic Name'
    required: true
  username:
    description: 'Username'
    required: true
  permission:
    description: 'Permission'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  admin-secret-id:
    description: 'Admin Secret ID in Secrets Manager'
    required: true

outputs:
  bootstrap-broker:
    description: 'Bootstrap Broker URL'
    value: ${{ steps.validation.outputs.bootstrap-broker }}
  cluster-arn:
    description: 'Cluster ARN'
    value: ${{ steps.validation.outputs.cluster-arn }}

runs:
  using: 'composite'
  steps:
    - name: Run All Validations
      id: validation
      shell: bash
      run: |
        export PATH=$PATH:/opt/kafka/bin

        AWS_REGION="${{ inputs.aws-region }}"
        CLUSTER_NAME="${{ inputs.cluster-name }}"
        TOPIC_NAME="${{ inputs.topic-name }}"
        USERNAME="${{ inputs.username }}"
        PERMISSION="${{ inputs.permission }}"
        ADMIN_SECRET_ID="${{ inputs.admin-secret-id }}"

        echo "══════════════════════════════════════"
        echo "🔍 Validation 1 - Finding cluster '$CLUSTER_NAME'..."
        echo "══════════════════════════════════════"

        CLUSTER_ARN=$(aws kafka list-clusters \
          --region "$AWS_REGION" \
          --cluster-name-filter "$CLUSTER_NAME" \
          --query 'ClusterInfoList[0].ClusterArn' \
          --output text 2>&1)

        if [ $? -ne 0 ] || [ "$CLUSTER_ARN" == "None" ] || [ -z "$CLUSTER_ARN" ]; then
          echo "❌ Cluster '$CLUSTER_NAME' NOT found!"
          exit 1
        fi

        echo "✅ Cluster found! ARN: $CLUSTER_ARN"

        echo ""
        echo "══════════════════════════════════════"
        echo "🔍 Validation 2 - Checking cluster state..."
        echo "══════════════════════════════════════"

        CLUSTER_STATE=$(aws kafka describe-cluster \
          --cluster-arn "$CLUSTER_ARN" \
          --region "$AWS_REGION" \
          --query 'ClusterInfo.State' \
          --output text)

        if [ "$CLUSTER_STATE" != "ACTIVE" ]; then
          echo "❌ Cluster is NOT ACTIVE! State: $CLUSTER_STATE"
          exit 1
        fi

        echo "✅ Cluster is ACTIVE!"

        echo ""
        echo "══════════════════════════════════════"
        echo "🔍 Validation 3 - Fetching broker..."
        echo "══════════════════════════════════════"

        BOOTSTRAP_BROKER=$(aws kafka get-bootstrap-brokers \
          --cluster-arn "$CLUSTER_ARN" \
          --region "$AWS_REGION" \
          --query 'BootstrapBrokerStringSaslScram' \
          --output text 2>&1)

        if [ $? -ne 0 ] || [ -z "$BOOTSTRAP_BROKER" ] || [ "$BOOTSTRAP_BROKER" == "None" ]; then
          echo "❌ Failed to get broker!"
          exit 1
        fi

        echo "✅ Broker: $BOOTSTRAP_BROKER"

        echo ""
        echo "══════════════════════════════════════"
        echo "🔍 Validation 4 - Creating client.properties..."
        echo "══════════════════════════════════════"

        ADMIN_USER="admin"

        echo "security.protocol=SASL_SSL" > ~/client.properties
        echo "sasl.mechanism=SCRAM-SHA-512" >> ~/client.properties
        echo "sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=\"$ADMIN_USER\" password=\"$ADMIN_SECRET_ID\";" >> ~/client.properties

        echo "✅ client.properties created!"
        cat ~/client.properties

        echo "✅ client.properties created!"

        echo ""
        echo "══════════════════════════════════════"
        echo "🔍 Validation 5 - Connecting to broker..."
        echo "══════════════════════════════════════"

        TOPICS=$(kafka-topics.sh \
          --bootstrap-server "$BOOTSTRAP_BROKER" \
          --command-config ~/client.properties \
          --list 2>&1)

        if [ $? -ne 0 ]; then
          echo "❌ Failed to connect to broker!"
          echo "   Error: $TOPICS"
          exit 1
        fi

        echo "✅ Connected! Total topics: $(echo "$TOPICS" | wc -l)"

    
        # Give admin CLUSTER ALL permission
        kafka-acls.sh \
          --bootstrap-server "$BOOTSTRAP_BROKER" \
          --command-config ~/client.properties \
          --add \
          --allow-principal "User:$USERNAME" \
          --operation "$PERMISSION" \
          --topic "$TOPIC_NAME" 2>&1

        if [ $? -ne 0 ]; then
          echo "❌ Failed to apply ACL!"
          exit 1
        fi

        echo "──────────────────────────────────────"
        echo "✅ ACL Applied Successfully!"
        echo "   User       : $USERNAME"
        echo "   Topic      : $TOPIC_NAME"
        echo "   Permission : $PERMISSION"
        echo "──────────────────────────────────────"
